# Global users and groups

- group_config:

    - cuhu_aem_default:

        - name: My Tetra Pak default group
          memberOf: everyone
          path: /home/groups/cuhugroups

    - cuhu_pack_design:

        - name: Package Design access
          memberOf: everyone
          path: /home/groups/cuhugroups
          
    - cuhu_pack_design_intro:

        - name: Package Design Intro Access
          memberOf: everyone
          path: /home/groups/cuhugroups

    - cuhu_pack_mat:

        - name: Packaging Material access
          memberOf: everyone
          path: /home/groups/cuhugroups

    - cuhu_parts:

        - name: Parts access
          memberOf: everyone
          path: /home/groups/cuhugroups

    - cuhu_marketplace:

        - name: Marketplace access
          memberOf: everyone
          path: /home/groups/cuhugroups

    - cuhu_partsinv:

        - name: Parts Inventory access
          memberOf: everyone
          path: /home/groups/cuhugroups

    - cuhu_partsinv_admin:

        - name: Parts Inventory Admin access
          memberOf: everyone
          path: /home/groups/cuhugroups

    - cuhu_aem_fin_soa:

        - name: Financials access
          memberOf: everyone
          path: /home/groups/cuhugroups

    - cuhu_tppm_access:

        - name: PlantMaster access
          memberOf: everyone
          path: /home/groups/cuhugroups
          
    - cuhu_aem_my_equip:
        - name: My Equipments access
          memberOf: everyone
          path: /home/groups/cuhugroups

    - cuhub_aem_rebuildingkits:
        - name: Rebuilding Kits Access
          memberOf: everyone
          path: /home/groups/cuhugroups

- ace_config:

    - cuhu_aem_default:

        - path: /content/dam
          permission: allow
          actions: read
          privileges:

        - path: /content/tetrapak/customerhub/global/en/dashboard
          permission: allow
          privileges: jcr:read

        - path: /content/tetrapak/customerhub/global/en/logout
          permission: allow
          privileges: jcr:read

        - path: /content/tetrapak/customerhub/global/en/error
          permission: allow
          privileges: jcr:read

        - path: /apps
          permission: allow
          actions: read
          privileges:

        - path: /content/tetrapak/customerhub/global/en/empty
          permission: allow
          privileges: jcr:read

        - path: /bin/customerhub
          permission: allow
          actions: read
          privileges:

        - path: /content/tetrapak/customerhub/content-components
          permission: allow
          actions: read
          privileges:

        - path: /content/tetrapak/customerhub
          permission: deny
          privileges: jcr:read,jcr:readAccessControl
          repGlob:

        - path: /content/tetrapak/customerhub
          permission: allow
          privileges: jcr:read,jcr:readAccessControl
          repGlob: ""

        - path: /content/tetrapak/customerhub
          permission: allow
          privileges: jcr:read,jcr:readAccessControl
          repGlob: /jcr:*

        - path: /content/tetrapak/customerhub/global/en
          permission: deny
          privileges: jcr:read,jcr:readAccessControl
          repGlob:

        - path: /content/tetrapak/customerhub/global/en
          permission: allow
          privileges: jcr:read,jcr:readAccessControl
          repGlob: ""

        - path: /content/tetrapak/customerhub/global/en
          permission: allow
          privileges: jcr:read,jcr:readAccessControl
          repGlob: /jcr:*

        - path: /content/tetrapak/customerhub/global/en/legal-information
          permission: allow
          privileges: jcr:read

    - cuhu_pack_design:

        - path: /content/tetrapak/customerhub/global/en/package-design/introduction
          permission: allow
          privileges: jcr:read

        - path: /content/tetrapak/customerhub/global/en/package-design
          permission: allow
          privileges: jcr:read
          
        - path: /content/tetrapak/customerhub/global/en/package-design/design-manual
          permission: allow
          privileges: jcr:read

        - path: /content/tetrapak/customerhub/global/en/package-design/package-visualiser
          permission: allow
          privileges: jcr:read
          
        - path: /content/tetrapak/customerhub/global/en/package-design/mydesigns
          permission: allow
          privileges: jcr:read        

    - cuhu_pack_design_intro:

        - path: /content/tetrapak/customerhub/global/en/package-design/introduction
          permission: allow
          privileges: jcr:read

        - path: /content/tetrapak/customerhub/global/en/package-design
          permission: allow
          privileges: jcr:read
          
        - path: /content/tetrapak/customerhub/global/en/package-design/design-manual
          permission: allow
          privileges: jcr:read

        - path: /content/tetrapak/customerhub/global/en/package-design/package-visualiser
          permission: allow
          privileges: jcr:read 

        - path: /content/tetrapak/customerhub/global/en/package-design/mydesigns
          permission: deny
          privileges: jcr:read          

    - cuhu_pack_mat:
        - path: /content/tetrapak/customerhub/global/en/ordering
          permission: deny
          privileges: jcr:read,jcr:readAccessControl
          repGlob:

        - path: /content/tetrapak/customerhub/global/en/ordering
          permission: allow
          privileges: jcr:read,jcr:readAccessControl
          repGlob: ""

        - path: /content/tetrapak/customerhub/global/en/ordering
          permission: allow
          privileges: jcr:read,jcr:readAccessControl
          repGlob: /jcr:*

        - path: /content/tetrapak/customerhub/global/en/ordering/packaging-material
          permission: allow
          actions: read
          privileges:         

    - cuhu_parts:
        - path: /content/tetrapak/customerhub/global/en/ordering
          permission: deny
          privileges: jcr:read,jcr:readAccessControl
          repGlob:

        - path: /content/tetrapak/customerhub/global/en/ordering
          permission: allow
          privileges: jcr:read,jcr:readAccessControl
          repGlob: ""

        - path: /content/tetrapak/customerhub/global/en/ordering
          permission: allow
          privileges: jcr:read,jcr:readAccessControl
          repGlob: /jcr:*

        - path: /content/tetrapak/customerhub/global/en/ordering/parts
          permission: allow
          actions: read
          privileges:

    - cuhu_marketplace:
        - path: /content/tetrapak/customerhub/global/en/ordering
          permission: deny
          privileges: jcr:read,jcr:readAccessControl
          repGlob:

        - path: /content/tetrapak/customerhub/global/en/ordering
          permission: allow
          privileges: jcr:read,jcr:readAccessControl
          repGlob: ""

        - path: /content/tetrapak/customerhub/global/en/ordering
          permission: allow
          privileges: jcr:read,jcr:readAccessControl
          repGlob: /jcr:*

        - path: /content/tetrapak/customerhub/global/en/ordering/marketplace
          permission: allow
          actions: read
          privileges:

    - cuhu_marketplace:
        - path: /content/tetrapak/customerhub/global/en/ordering
          permission: deny
          privileges: jcr:read,jcr:readAccessControl
          repGlob:

        - path: /content/tetrapak/customerhub/global/en/ordering
          permission: allow
          privileges: jcr:read,jcr:readAccessControl
          repGlob: ""

        - path: /content/tetrapak/customerhub/global/en/ordering
          permission: allow
          privileges: jcr:read,jcr:readAccessControl
          repGlob: /jcr:*

        - path: /content/tetrapak/customerhub/global/en/ordering/marketplace
          permission: allow
          actions: read
          privileges:

    - cuhu_partsinv:

        - path: /content/tetrapak/customerhub/global/en/parts-inventory
          permission: allow
          actions: read
          privileges:

    - cuhu_partsinv_admin:

        - path: /content/tetrapak/customerhub/global/en/parts-inventory-admin
          permission: allow
          actions: read
          privileges:
          
    - cuhu_aem_fin_soa:

        - path: /content/tetrapak/customerhub/global/en/financials
          permission: allow
          privileges: jcr:read

    - cuhu_tppm_access:

        - path: /content/tetrapak/customerhub/global/en/automation-digital
          permission: allow
          privileges: jcr:read
              
    - cuhu_aem_my_equip:

        - path: /content/tetrapak/customerhub/global/en/installed-equipments
          permission: deny
          privileges: jcr:read,jcr:readAccessControl
          repGlob:

        - path: /content/tetrapak/customerhub/global/en/installed-equipments
          permission: allow
          privileges: jcr:read,jcr:readAccessControl
          repGlob: ""

        - path: /content/tetrapak/customerhub/global/en/installed-equipments
          permission: allow
          privileges: jcr:read,jcr:readAccessControl
          repGlob: /jcr:*
          
        - path:  /content/tetrapak/customerhub/global/en/installed-equipments/equipments
          permission: allow
          privileges: jcr:read
          
        - path:  /content/tetrapak/customerhub/global/en/installed-equipments/equipments/equipment-details
          permission: allow
          privileges: jcr:read
          
        - path:  /content/tetrapak/customerhub/global/en/installed-equipments/equipments/add-equipment
          permission: allow
          privileges: jcr:read
          
        - path:  /content/tetrapak/customerhub/global/en/installed-equipments/technical-publication
          permission: allow
          privileges: jcr:read

    - cuhub_aem_rebuildingkits:

        - path: /content/tetrapak/customerhub/global/en/installed-equipments
          permission: deny
          privileges: jcr:read,jcr:readAccessControl
          repGlob:

        - path: /content/tetrapak/customerhub/global/en/installed-equipments
          permission: allow
          privileges: jcr:read,jcr:readAccessControl
          repGlob: ""

        - path: /content/tetrapak/customerhub/global/en/installed-equipments
          permission: allow
          privileges: jcr:read,jcr:readAccessControl
          repGlob: /jcr:*

        - path: /content/tetrapak/customerhub/global/en/installed-equipments/rebuilding-kits
          permission: allow
          privileges: jcr:read
