
# Trs users and groups

- group_config:

    - cuhu_training_edcast:

        - name: Edcast users
          memberOf: everyone
          path: /home/groups/cuhugroups
          
    - cuhu_training_anytimelearning:

        - name: Edcast Internal Users
          memberOf: everyone
          path: /home/groups/cuhugroups


- ace_config:

    - cuhu_training_edcast:
    
        - path: /
          permission: allow
          actions:
          privileges: jcr:read
          repGlob: ""

        - path: /content
          permission: allow
          actions:
          privileges: jcr:read
          repGlob: ""

        - path: /content/trs
          permission: allow
          actions: read
          initialContent: |
                            <jcr:root jcr:primaryType="cq:Page">
                            </jcr:root> 
          
    - cuhu_training_anytimelearning:

        - path: /
          permission: allow
          actions:
          privileges: jcr:read
          repGlob: ""

        - path: /content
          permission: allow
          actions:
          privileges: jcr:read
          repGlob: ""

        - path: /content/trs
          permission: allow
          actions: read
