# Global users and groups

- group_config:

    - sp_global_authors:

        - name: Supplier portal global content authors group
          memberOf: content-authors
          path: /home/groups/spgroups
- ace_config:

    - sp_global_authors:

        - path: /content
          permission: deny
          privileges: jcr:modifyAccessControl,crx:replicate,jcr:versionManagement,rep:write,jcr:lockManagement

        - path: /content/tetrapak
          permission: allow
          privileges: jcr:read,jcr:readAccessControl

        - path: /content/dam/tetrapak
          permission: allow
          privileges: jcr:read,jcr:readAccessControl

        - path: /content/tetrapak/supplierportal
          permission: allow
          privileges: jcr:modifyAccessControl,jcr:read,jcr:readAccessControl,crx:replicate,jcr:versionManagement,rep:write,jcr:lockManagement

        - path: /content/dam/tetrapak/supplierportal
          permission: allow
          privileges: jcr:modifyAccessControl,jcr:read,jcr:readAccessControl,crx:replicate,jcr:versionManagement,rep:write,jcr:lockManagement

        - path: /etc/languages
          permission: allow
          actions: read
          privileges:
