# Publicweb groups

- group_config:

    - publicweb-basic:

        - name: "Public Web Basic Access"
          isMemberOf:
          path: /home/groups/publicweb


    - publicweb-content-editors-se:

       - name: "Public Web Content Authors for Sweden"
         isMemberOf: fragment-editor,publicweb-basic
         path: /home/groups/publicweb

    - publicweb-content-owners-se:

       - name: "Public Web Content Owners for Sweden"
         isMemberOf: fragment-editor,publicweb-basic
         path: /home/groups/publicwebgroups

- ace_config:

    - publicweb-basic:

        - path: /content/tetrapak
          permission: allow
          actions:
          privileges: jcr:read,jcr:readAccessControl
          repGlob: ""

        - path: /content/tetrapak
          permission: allow
          actions:
          privileges: jcr:read,jcr:readAccessControl
          repGlob: /jcr:content

        - path: /content/tetrapak/publicweb
          permission: allow
          actions:
          privileges: jcr:read,jcr:readAccessControl
          repGlob: ""

        - path: /content/tetrapak/publicweb
          permission: allow
          actions:
          privileges: jcr:read,jcr:readAccessControl
          repGlob: /jcr:content

        - path: /content/dam/tetrapak
          permission: allow
          actions:
          privileges: jcr:read,jcr:readAccessControl
          repGlob: ""

        - path: /content/dam/tetrapak
          permission: allow
          actions:
          privileges: jcr:read,jcr:readAccessControl
          repGlob: /jcr:content

        - path: /content/dam/tetrapak/publicweb
          permission: allow
          actions:
          privileges: jcr:read,jcr:readAccessControl
          repGlob: ""

        - path: /content/dam/tetrapak/publicweb
          permission: allow
          actions:
          privileges: jcr:read,jcr:readAccessControl
          repGlob: /jcr:content

        - path: /conf/publicweb/settings/wcm
          permission: allow
          actions: read
          privileges:
          repGlob:

        - path: /content/cq:tags/tetrapak
          permission: allow
          actions: read
          privileges:
          repGlob:

    - publicweb-content-editors-se:

        - path: /content/tetrapak/publicweb/se
          permission: allow
          actions: read,modify,create
          privileges:
          repGlob:

        - path: /content/dam/tetrapak/publicweb/se
          permission: allow
          actions: read,modify,create,delete,replicate
          privileges:
          repGlob:

        - path: /content/dam/tetrapak/publicweb/gb
          permission: allow
          actions: read
          privileges:
          repGlob:

    - publicweb-content-owners-se:

        - path: /content/tetrapak/publicweb/se
          permission: allow
          actions: read,modify,create,delete,replicate
          privileges:
          repGlob:

        - path: /content/dam/tetrapak/publicweb/se
          permission: allow
          actions: read,modify,create,delete,replicate
          privileges:
          repGlob:

        - path: /content/dam/tetrapak/publicweb/gb
          permission: allow
          actions: read
          privileges:
          repGlob: