# Publicweb groups

- group_config:

    - publicweb-basic:

        - name: "Public Web Basic Access"
          isMemberOf:
          path: /home/groups/publicweb


- ace_config:

    - publicweb-basic:

        - path: /content/tetrapak
          permission: allow
          actions:
          privileges: jcr:read,jcr:readAccessControl
          repGlob: ""

        - path: /content/tetrapak
          permission: allow
          actions:
          privileges: jcr:read,jcr:readAccessControl
          repGlob: /jcr:content

        - path: /content/tetrapak/publicweb
          permission: allow
          actions:
          privileges: jcr:read,jcr:readAccessControl
          repGlob: ""

        - path: /content/tetrapak/publicweb
          permission: allow
          actions:
          privileges: jcr:read,jcr:readAccessControl
          repGlob: /jcr:content

        - path: /content/dam/tetrapak
          permission: allow
          actions:
          privileges: jcr:read,jcr:readAccessControl
          repGlob: ""

        - path: /content/dam/tetrapak
          permission: allow
          actions:
          privileges: jcr:read,jcr:readAccessControl
          repGlob: /jcr:content

        - path: /content/dam/tetrapak/publicweb
          permission: allow
          actions:
          privileges: jcr:read,jcr:readAccessControl
          repGlob: ""

        - path: /content/dam/tetrapak/publicweb
          permission: allow
          actions:
          privileges: jcr:read,jcr:readAccessControl
          repGlob: /jcr:content

        - path: /content/dam/tetrapak/media-box
          permission: allow
          actions: read
          privileges:
          repGlob:

        - path: /conf/publicweb/settings/wcm
          permission: allow
          actions: read
          privileges:
          repGlob:

        - path: /etc/mobile/groups/responsive
          permission: allow
          actions: read
          privileges:
          repGlob:

        - path: /content/cq:tags/tetrapak
          permission: allow
          actions: read
          privileges:
          repGlob: